Use a one-liner to skip files that aren't for daisyproducer

diff --git a/roles/daisyproducer2/templates/daisyproducer2_abacus_import.j2 b/roles/daisyproducer2/templates/daisyproducer2_abacus_import.j2
--- a/roles/daisyproducer2/templates/daisyproducer2_abacus_import.j2
+++ b/roles/daisyproducer2/templates/daisyproducer2_abacus_import.j2
@@ -17,23 +17,19 @@ FILES="${SPOOL_DIR}/SN_Alfresco_*.xml"
 
 for file in $FILES ; do
     if [ -e "$file" ] ; then # make sure it isn't an empty match
-	if grep --quiet "<daisy_producer>nein</daisy_producer>" "$file"
-	then
-	    # the file is not meant for daisyproducer2, drop it
-	    rm "$file"
+	# drop files that aren't meant for daisyproducer2
+	grep --quiet "<daisy_producer>nein</daisy_producer>" "$file" && rm -f "$file" && continue
+        RESULT=$(curl -i -X 'POST' $URL -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F "file=@${file};type=text/xml" --silent --fail --show-error)
+	if echo "$RESULT" | grep --extended-regexp --quiet "$REGEXP"
+	then mv "$file" $SPOOL_DIR/processed/
 	else
-            RESULT=$(curl -i -X 'POST' $URL -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F "file=@${file};type=text/xml" --silent --fail --show-error)
-	    if echo "$RESULT" | grep --extended-regexp --quiet "$REGEXP"
-	    then mv "$file" $SPOOL_DIR/processed/
-	    else
-		echo >&2 "Moving file to $SPOOL_DIR/invalid/"
-		mv "$file" "$SPOOL_DIR"/invalid/
-		printf >&2 '\n%s\n%s\n\n' "Daisproducer2 response:" "$RESULT"
-		grep --extended-regexp >&2 \
-		     'artikel_nr|identifier|date|title|idVorstufe|process_status' \
-		     $SPOOL_DIR/invalid/${file##*/}
-		echo >&2 "========================================="
-	    fi
+	    echo >&2 "Moving file to $SPOOL_DIR/invalid/"
+	    mv "$file" "$SPOOL_DIR"/invalid/
+	    printf >&2 '\n%s\n%s\n\n' "Daisproducer2 response:" "$RESULT"
+	    grep --extended-regexp >&2 \
+		 'artikel_nr|identifier|date|title|idVorstufe|process_status' \
+		 $SPOOL_DIR/invalid/${file##*/}
+	    echo >&2 "========================================="
 	fi
     fi
 done
